export const LOCALHOST_FRONT = 'localhost:8888'
export const LOCALHOST_BACKEND = 'localhost:8000'
// export const SERVERIP_FRONTEND = '35.192.228.224'
export const SERVERIP_FRONTEND = LOCALHOST_FRONT
export const SERVERIP_BACKEND = LOCALHOST_BACKEND